name: monitoring
publish_to: none

environment:
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.17.1
  firebase_crashlytics: ^2.8.1
  firebase_dynamic_links: ^2.0.7
  firebase_analytics: ^9.1.9
  firebase_remote_config: ^2.0.8
  package_info: ^2.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8