name: fav_qs_api
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  equatable: ^2.0.3
  json_annotation: ^4.0.1

dev_dependencies:
  mocktail: 0.1.4
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  test: ^1.16.8
  lints: ^1.0.1